# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parseBamFileCpp <- function(fileName, binSize) {
    .Call('_msscaf_parseBamFileCpp', PACKAGE = 'msscaf', fileName, binSize)
}

computeMeanTrianglesCpp <- function(data, distance, metaSize, sizesIn, outliers) {
    .Call('_msscaf_computeMeanTrianglesCpp', PACKAGE = 'msscaf', data, distance, metaSize, sizesIn, outliers)
}

removeNearEqualBreaksCpp <- function(breaks, distance) {
    .Call('_msscaf_removeNearEqualBreaksCpp', PACKAGE = 'msscaf', breaks, distance)
}

computeCornerSize <- function(size1, size2, maxDistance) {
    .Call('_msscaf_computeCornerSize', PACKAGE = 'msscaf', size1, size2, maxDistance)
}

filterCornersCpp <- function(data, sizesIn, cornerSize, metaSize) {
    .Call('_msscaf_filterCornersCpp', PACKAGE = 'msscaf', data, sizesIn, cornerSize, metaSize)
}

sumCornerCpp <- function(interactions, outliers, sizesIn, cornerSize, metaSize) {
    .Call('_msscaf_sumCornerCpp', PACKAGE = 'msscaf', interactions, outliers, sizesIn, cornerSize, metaSize)
}

extractCornersCpp <- function(interactions, selectedRefs, outliers, sizesIn, cornerSize, metaSize) {
    .Call('_msscaf_extractCornersCpp', PACKAGE = 'msscaf', interactions, selectedRefs, outliers, sizesIn, cornerSize, metaSize)
}

classifyCornerPointsCpp <- function(interactions, size1, size2, metaSize, maxDistance) {
    .Call('_msscaf_classifyCornerPointsCpp', PACKAGE = 'msscaf', interactions, size1, size2, metaSize, maxDistance)
}

extractCornersFullCpp <- function(interactions, selectedCorners, outliers, sizesIn, cornerSize, metaSize) {
    .Call('_msscaf_extractCornersFullCpp', PACKAGE = 'msscaf', interactions, selectedCorners, outliers, sizesIn, cornerSize, metaSize)
}

computeCornerDifferenceOffsetCpp <- function(offset, corner, background, maxDistance) {
    .Call('_msscaf_computeCornerDifferenceOffsetCpp', PACKAGE = 'msscaf', offset, corner, background, maxDistance)
}

computeCornerDifferenceBothOffsetCpp <- function(offset, corner, background, maxDistance) {
    .Call('_msscaf_computeCornerDifferenceBothOffsetCpp', PACKAGE = 'msscaf', offset, corner, background, maxDistance)
}

estimateDistanceCountCpp <- function(data, outliers, sizesIn, distance, metaSize, nOutputElements) {
    .Call('_msscaf_estimateDistanceCountCpp', PACKAGE = 'msscaf', data, outliers, sizesIn, distance, metaSize, nOutputElements)
}

sampleTriangles <- function(data, outliers, sizesIn, distance, metaSize, nSamples) {
    .Call('_msscaf_sampleTriangles', PACKAGE = 'msscaf', data, outliers, sizesIn, distance, metaSize, nSamples)
}

estimateMetaSizeCpp <- function(rowAvg, maxDistance, nMeta, minCount) {
    .Call('_msscaf_estimateMetaSizeCpp', PACKAGE = 'msscaf', rowAvg, maxDistance, nMeta, minCount)
}

estimateMoleculeSizeCpp <- function(metaSums, maxDistance, minCount, metaSize) {
    .Call('_msscaf_estimateMoleculeSizeCpp', PACKAGE = 'msscaf', metaSums, maxDistance, minCount, metaSize)
}

estimateMaxMoleculeSizeCpp <- function(metaSums, minDistance, maxDistance, minCount, metaSize) {
    .Call('_msscaf_estimateMaxMoleculeSizeCpp', PACKAGE = 'msscaf', metaSums, minDistance, maxDistance, minCount, metaSize)
}

estimateMetaBinsMoleculeSizeCpp <- function(data, sizes, minCount, nMeta, moleculeSize) {
    .Call('_msscaf_estimateMetaBinsMoleculeSizeCpp', PACKAGE = 'msscaf', data, sizes, minCount, nMeta, moleculeSize)
}

keepScaffoldsCpp <- function(data, keptRefs) {
    .Call('_msscaf_keepScaffoldsCpp', PACKAGE = 'msscaf', data, keptRefs)
}

keepScaffoldsPairsCpp <- function(data, keptRefs) {
    .Call('_msscaf_keepScaffoldsPairsCpp', PACKAGE = 'msscaf', data, keptRefs)
}

extractLines <- function(matrix, lines, maxDistance) {
    .Call('_msscaf_extractLines', PACKAGE = 'msscaf', matrix, lines, maxDistance)
}

splitChromosomeCpp <- function(data, prevRef, newRef, shiftedRef, splitPoint, firstPart) {
    invisible(.Call('_msscaf_splitChromosomeCpp', PACKAGE = 'msscaf', data, prevRef, newRef, shiftedRef, splitPoint, firstPart))
}

computeRefSizesCpp <- function(data) {
    .Call('_msscaf_computeRefSizesCpp', PACKAGE = 'msscaf', data)
}

computeNRrows <- function(data, sizes) {
    .Call('_msscaf_computeNRrows', PACKAGE = 'msscaf', data, sizes)
}

computeSymmetricColSum <- function(data, sizes) {
    .Call('_msscaf_computeSymmetricColSum', PACKAGE = 'msscaf', data, sizes)
}

computeSymmetricColSumMeta <- function(data, sizes, metaSize) {
    .Call('_msscaf_computeSymmetricColSumMeta', PACKAGE = 'msscaf', data, sizes, metaSize)
}

removeLowCountRowsCpp <- function(data, sizes, threshold) {
    .Call('_msscaf_removeLowCountRowsCpp', PACKAGE = 'msscaf', data, sizes, threshold)
}

normalizeHighCountRowsCpp <- function(data, sizes) {
    invisible(.Call('_msscaf_normalizeHighCountRowsCpp', PACKAGE = 'msscaf', data, sizes))
}

parseHicCpp <- function(fname, resolution) {
    .Call('_msscaf_parseHicCpp', PACKAGE = 'msscaf', fname, resolution)
}

makeSymmetricRefCpp <- function(data) {
    .Call('_msscaf_makeSymmetricRefCpp', PACKAGE = 'msscaf', data)
}

removeOutliersRefCpp <- function(data, outliersTibble, size, minLim = -1L, maxLim = -1L) {
    .Call('_msscaf_removeOutliersRefCpp', PACKAGE = 'msscaf', data, outliersTibble, size, minLim, maxLim)
}

removeOutliersCpp <- function(data, outliersTibble, sizes) {
    .Call('_msscaf_removeOutliersCpp', PACKAGE = 'msscaf', data, outliersTibble, sizes)
}

parsePafCpp <- function(fname, resolution, minAlnLen, minCount, minNCells) {
    .Call('_msscaf_parsePafCpp', PACKAGE = 'msscaf', fname, resolution, minAlnLen, minCount, minNCells)
}

getRefOrders <- function(joins, sizes) {
    .Call('_msscaf_getRefOrders', PACKAGE = 'msscaf', joins, sizes)
}

scaffoldSizes <- function(orders, orderIds, sizes) {
    .Call('_msscaf_scaffoldSizes', PACKAGE = 'msscaf', orders, orderIds, sizes)
}

scaffoldContigs <- function(contigs, orders, sizes, binSize) {
    .Call('_msscaf_scaffoldContigs', PACKAGE = 'msscaf', contigs, orders, sizes, binSize)
}

scaffoldCounts <- function(matrices, outlierBins, groups, scaffoldRefs, sizes, metaSize) {
    .Call('_msscaf_scaffoldCounts', PACKAGE = 'msscaf', matrices, outlierBins, groups, scaffoldRefs, sizes, metaSize)
}

splitCpp <- function(object) {
    .Call('_msscaf_splitCpp', PACKAGE = 'msscaf', object)
}

