# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parseBamFileCpp <- function(fileName, binSize) {
    .Call('_tenxchecker_parseBamFileCpp', PACKAGE = 'tenxchecker', fileName, binSize)
}

computeMeanTrianglesCpp <- function(data, distance, sizes, outliers) {
    .Call('_tenxchecker_computeMeanTrianglesCpp', PACKAGE = 'tenxchecker', data, distance, sizes, outliers)
}

removeNearEqualBreaksCpp <- function(breaks, distance) {
    .Call('_tenxchecker_removeNearEqualBreaksCpp', PACKAGE = 'tenxchecker', breaks, distance)
}

computeCornerSize <- function(size1, size2, maxDistance) {
    .Call('_tenxchecker_computeCornerSize', PACKAGE = 'tenxchecker', size1, size2, maxDistance)
}

filterCornersCpp <- function(data, sizes, cornerSize) {
    .Call('_tenxchecker_filterCornersCpp', PACKAGE = 'tenxchecker', data, sizes, cornerSize)
}

extractCornersCpp <- function(interactions, selectedRefs, sizes, cornerSize) {
    .Call('_tenxchecker_extractCornersCpp', PACKAGE = 'tenxchecker', interactions, selectedRefs, sizes, cornerSize)
}

classifyCornerPointsCpp <- function(interactions, size1, size2, maxDistance) {
    .Call('_tenxchecker_classifyCornerPointsCpp', PACKAGE = 'tenxchecker', interactions, size1, size2, maxDistance)
}

estimateDistanceCountCpp <- function(data, outliers, sizes, distance) {
    .Call('_tenxchecker_estimateDistanceCountCpp', PACKAGE = 'tenxchecker', data, outliers, sizes, distance)
}

keepScaffoldsCpp <- function(data, keptRefs) {
    .Call('_tenxchecker_keepScaffoldsCpp', PACKAGE = 'tenxchecker', data, keptRefs)
}

keepScaffoldsPairsCpp <- function(data, keptRefs) {
    .Call('_tenxchecker_keepScaffoldsPairsCpp', PACKAGE = 'tenxchecker', data, keptRefs)
}

extractLines <- function(matrix, lines, maxDistance) {
    .Call('_tenxchecker_extractLines', PACKAGE = 'tenxchecker', matrix, lines, maxDistance)
}

splitChromosomeCpp <- function(data, prevRef, newRef, shiftedRef, splitPoint, firstPart) {
    invisible(.Call('_tenxchecker_splitChromosomeCpp', PACKAGE = 'tenxchecker', data, prevRef, newRef, shiftedRef, splitPoint, firstPart))
}

computeRefSizesCpp <- function(data) {
    .Call('_tenxchecker_computeRefSizesCpp', PACKAGE = 'tenxchecker', data)
}

computeNRrows <- function(data, sizes) {
    .Call('_tenxchecker_computeNRrows', PACKAGE = 'tenxchecker', data, sizes)
}

computeSymmetricColSum <- function(data, sizes) {
    .Call('_tenxchecker_computeSymmetricColSum', PACKAGE = 'tenxchecker', data, sizes)
}

removeLowCountRowsCpp <- function(data, sizes, threshold) {
    .Call('_tenxchecker_removeLowCountRowsCpp', PACKAGE = 'tenxchecker', data, sizes, threshold)
}

normalizeHighCountRowsCpp <- function(data, sizes) {
    invisible(.Call('_tenxchecker_normalizeHighCountRowsCpp', PACKAGE = 'tenxchecker', data, sizes))
}

parseHicCpp <- function(fname, resolution) {
    .Call('_tenxchecker_parseHicCpp', PACKAGE = 'tenxchecker', fname, resolution)
}

makeSymmetricRefCpp <- function(data) {
    .Call('_tenxchecker_makeSymmetricRefCpp', PACKAGE = 'tenxchecker', data)
}

removeOutliersRefCpp <- function(data, outliersTibble, size, minLim = -1L, maxLim = -1L) {
    .Call('_tenxchecker_removeOutliersRefCpp', PACKAGE = 'tenxchecker', data, outliersTibble, size, minLim, maxLim)
}

parsePafCpp <- function(fname, resolution, minAlnLen, minCount, minNCells) {
    .Call('_tenxchecker_parsePafCpp', PACKAGE = 'tenxchecker', fname, resolution, minAlnLen, minCount, minNCells)
}

getRefOrders <- function(joins, sizes) {
    .Call('_tenxchecker_getRefOrders', PACKAGE = 'tenxchecker', joins, sizes)
}

scaffoldSizes <- function(orders, orderIds, sizes) {
    .Call('_tenxchecker_scaffoldSizes', PACKAGE = 'tenxchecker', orders, orderIds, sizes)
}

scaffoldContigs <- function(contigs, orders, sizes, binSize) {
    .Call('_tenxchecker_scaffoldContigs', PACKAGE = 'tenxchecker', contigs, orders, sizes, binSize)
}

scaffoldCounts <- function(matrices, groups, scaffoldRefs, sizes) {
    .Call('_tenxchecker_scaffoldCounts', PACKAGE = 'tenxchecker', matrices, groups, scaffoldRefs, sizes)
}

splitCpp <- function(object) {
    .Call('_tenxchecker_splitCpp', PACKAGE = 'tenxchecker', object)
}

