# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parseBamFileCpp <- function(fileName, binSize, nThreads) {
    .Call(`_tenxchecker_parseBamFileCpp`, fileName, binSize, nThreads)
}

parseHicCpp <- function(fname, resolution) {
    .Call(`_tenxchecker_parseHicCpp`, fname, resolution)
}

parsePafCpp <- function(fname, resolution, minAlnLen, minCount, minNCells) {
    .Call(`_tenxchecker_parsePafCpp`, fname, resolution, minAlnLen, minCount, minNCells)
}

